name: steeker
description: Discord emojis to stickers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sentry_flutter: ^6.0.1
  http: ^0.13.3
  dio: ^4.0.0
  firebase_performance: ^0.7.1+1
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  flutter_appauth: ^1.1.0+2
  flutter_secure_storage: ^4.2.1
  flutter_conditional_rendering: ^2.0.0
  fluttertoast: ^8.0.8
  loading_overlay: ^0.3.0
  flutter_whatsapp_stickers: ^1.0.0+5
  package_info: ^2.0.2
  url_launcher: ^6.0.12
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
